# CFLAGS= -Wall -fpic -coverage -std=c99 -g

all: # testme.o testme
	gcc -Wall -fpic -coverage -std=c99 -g -o testme testme.c && ./testme

# testme: testme.o
# 	gcc -o RUN testme.o && ./testme

# testme.o: testme.c
# 	gcc -Wall -fpic -coverage -std=c99 -g -o testme testme.c && ./testme
	# gcc $(CFLAGS) -o testme testme.c
